name: CI

on:
  push:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment info
        run: |
          echo "Current directory:"
          pwd
          echo "Files in repo:"
          ls -R

  test:
    needs: inspect
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify README exists
        run: |
          echo "Checking for README.md..."
          test -f README.md
          echo "README exists ✔"


  build:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/cicd-lab:latest .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}/cicd-lab:latest
